### PR TITLE
Add a Responsive Shoe Website

### PR DESCRIPTION
**Pull request by amanver45**
#512 

Screenshot 2024-10-22 225549
Screenshot 2024-10-22 230153

### CODE REVIEW

**Comment by beRajeevKumar** [comment]
check it one more time and run it on the local system then raise PR.

**Comment by amanver45** [comment]
@beRajeevKumar i  fix the issue pls check

**Comment by beRajeevKumar** [comment]
Thanks, Aman, for your contribution

**Review by RadhikaMalpani1702 — COMMENTED** [review]
@mastansayyad @sanjay-kv review this PR

**Comment by sanjay-kv** [comment]
this looks fine

**Comment by MastanSayyad** [comment]
@sanjay-kv the repository is about project additions/directory there is no possible way that an indvisual can create such website with complete responsiveness in short period so need to reduce labels as the PR is not related to repos website developement instead repos projects additions same goes to other PR too

image

**Comment by sanjay-kv** [comment]
alright, i didnt went deep, 
lets dowgrade

**Pull request merged**
