### PR TITLE
Added missing images and made it mobile responsive in 9-Clipboard Landing Page

### PR DESCRIPTION
**Pull request by J-B-Mugundh**
Purpose:
This PR adds missing images and improves the mobile responsiveness of the 9-Clipboard Landing Page.

Description:

- Added missing images (Issue with old path).
- Enhanced mobile responsiveness with media queries to adjust layout on smaller screens.
- Optimized images, buttons, and text alignment for better mobile experience.

Benefits:

- Improved User Experience: Ensures a seamless, responsive design across all devices.
- Consistency: Maintains visual integrity and functionality on mobile.

Related issues:
#63 

Screenshots:
image

image

image

### CODE REVIEW

**Comment by J-B-Mugundh** [comment]
@beRajeevKumar Please review this PR and let me know if any changes required. Also, add gssoc-extd and hacktoberfest labels. Thank you

**Comment by beRajeevKumar** [comment]
Nice work @J-B-Mugundh 👍🏻

**Comment by J-B-Mugundh** [comment]
> Nice work @J-B-Mugundh 👍🏻

Thank you! Could you add the labels as well, please?

**Comment by J-B-Mugundh** [comment]
@beRajeevKumar @shreyajaiswal17 @AkshitGarg24 @KiranBaliga @priyaahm @himanshu-sheetlani @pankaj1132 @jjf2009 Could someone please add gssoc-extd and hacktoberfest labels

**Comment by AkshitGarg24** [comment]
Done @J-B-Mugundh .

Do one more thing. Edit the description of PR and add the line "Fixes #63 "

**Comment by J-B-Mugundh** [comment]
> Done @J-B-Mugundh .
> 
> Do one more thing. Edit the description of PR and add the line "Fixes #63 "

Sure! Updated

**Comment by J-B-Mugundh** [comment]
@AkshitGarg24 Could u please add level label as well..

**Pull request merged**
