### PR TITLE
Add responsive restaurant website (Zaika Palace

### PR DESCRIPTION
**Pull request by amanver45**
issue #414

Implement a responsive design for the restaurant website, ensuring it adapts seamlessly across various devices including mobile, tablet, and desktop. The design should prioritize user experience and easy navigation, with menus, booking options, and other essential features accessible on all screen sizes.
- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

https://github.com/user-attachments/assets/de658790-0fc8-4432-9728-6a9eff2d3c53

### CODE REVIEW

**Comment by amanver45** [comment]
@beRajeevKumar sir pls check pr and merge it

**Comment by beRajeevKumar** [comment]
Nice Work @amanver45

**Review by RadhikaMalpani1702 — COMMENTED** [review]
@mastansayyad @sanjay-kv can you review this PR

**Comment by sanjay-kv** [comment]
This is fine

**Pull request merged**
