### PR TITLE
Fixed navbar logo

### LINKED ISSUE #128: fix navbar logo
image
The logo in navbar is looking ugly with the white background. I want to fix this issue. Plz assign me this issue with gssoc-ext, hacktoberfest-accepted and level1 labels @beRajeevKumar

### PR DESCRIPTION
**Pull request by devarsheecodess**
## What does this PR do?
fixes navbar logo

Fixes #128

## Type of change
- Bug fix (non-breaking change which fixes an issue)
- Chore (refactoring code, technical debt, workflow improvements)

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by devarsheecodess** [comment]
@beRajeevKumar , i have resolved the conflicts

**Comment by AkshitGarg24** [comment]
@devarsheecodess, I don't find any changes you have made to the updated website.

**Comment by devarsheecodess** [comment]
it is because you have not merged my PR, the logo had a background which i had removed from the navbar
Here is the screenshot
image

**Comment by AkshitGarg24** [comment]
@devarsheecodess, keep yourself up-to-date with the original website link to avoid such issues.

**Comment by devarsheecodess** [comment]
Ohh my bad, np, i will find some other issue

**Pull request closed without merging**
