### PR TITLE
Add mini chabot to the website

### PR DESCRIPTION
**Pull request by ruchikakengal**
#92 fixed Add mini chatbot 
This chatbot gives quike response to the users any questions 
Add gssoc-ext,hactoberfast accepted and level 3 to this pr @beRajeevKumar 
Screenrecording

Uploading Screen Recording 2024-10-07 150125.mp4…

### CODE REVIEW

**Comment by ruchikakengal** [comment]
Screenrecording

https://github.com/user-attachments/assets/55123ba7-8feb-4f7a-be54-1636734609b2

@beRajeevKumar

**Comment by AkshitGarg24** [comment]
@ruchikakengal, the website has undergone some UI updates. Please update your branch and resolve any conflicts. I’ll review the PR once it's ready.

**Comment by ruchikakengal** [comment]
Resolve the conflicts @beRajeevKumar

**Comment by AkshitGarg24** [comment]
The whole footer will get messed @ruchikakengal. Have a look at this screenshot : 

Screenshot 2024-10-08 220748

**Comment by ruchikakengal** [comment]
#161 fixed the issue.

**Review by ruchikakengal — COMMENTED** [review]
#161 fixed the issue

**Comment by AkshitGarg24** [comment]
The UI is not properly fixed. Here is the link of the website which will appear after merging your PR : [LINK](https://deploy-preview-161--openfrontendmentor.netlify.app/)

**Comment by ruchikakengal** [comment]
Reslove the conflicts @beRajeevKumar 
Add lables gossoc-ext ,hacktoberfest and lavel 3.

**Pull request merged**
