### PR TITLE
Added a Html and css to resolve the issue on testimonial grid section.

### PR DESCRIPTION
**Pull request by kenzo0p**
in this your solution there is only one para of testimonal grid section so add my style to contribute on it . and now its perfect.

### CODE REVIEW

**Comment by kenzo0p** [comment]
issue is solved .

**Comment by kenzo0p** [comment]
This contribution is a part of GSSOC'24  can you please add the label ..

**Comment by AkshitGarg24** [comment]
@kenzo0p, the website has undergone some UI updates. Please update your branch and resolve any conflicts. I’ll review the PR once it's ready.

**Comment by kenzo0p** [comment]
@AkshitGarg24 non any conflicts i would also like to add more projects as I am also using frontendmentor for prcatice

**Comment by AkshitGarg24** [comment]
@kenzo0p, your branch is not updated. Please update the branch. And for projects, yes you can make.

**Comment by kenzo0p** [comment]
hii can you help me with cosnlicts @AkshitGarg24

**Comment by kenzo0p** [comment]
please add gssoc labels

**Pull request merged**
