### PR TITLE
Fixed: Readme Error and Added Project 22 To website

### PR DESCRIPTION
**Pull request by jjf2009**
Issue #13 
The readme file is updated according to the order in the website , the demo link directly takes u to the deployed website, the code link takes u to the index.html file and the blog link takes u to the readme file of the respective project .
Screenshots :-
1.
Screenshot 2024-10-02 100309
2.
Screenshot 2024-10-02 100324

### CODE REVIEW

**Review by beRajeevKumar — COMMENTED** [review]
There is some more work in it, @jjf2009 work some other issue of the project.

**Comment by jjf2009** [comment]
ok

**Comment by beRajeevKumar** [comment]
@jjf2009, Bro, some projects will also be added to this repo in just 2/3 days then you will update this readme again, and then I will merge this PR.

**Comment by jjf2009** [comment]
@beRajeevKumar ok no problem but can u please add labels to the PRs that are merged so that i come on the leaderboard please

**Comment by jjf2009** [comment]
@beRajeevKumar please add labels to one of my merged PR  sorry for disturbing you u bro

**Pull request closed without merging**
