### PR TITLE
Fixed the bugs in project "12-Huddle-comm-page".#51

### PR DESCRIPTION
**Pull request by pranjalee30**
I fixed three bugs and enhanced the responsive UI. For Bug 01, I optimized social icons by reducing load time. For Bug 02, I adjusted the footer text positioning to ensure it stays at the bottom, maintaining the original design layout. For Bug 03, I refined the mobile version to match the exact mobile design provided in the design directory. Additionally, I improved the CSS to create a more responsive and user-friendly interface across all devices.#51

### CODE REVIEW

**Comment by pranjalee30** [comment]
@beRajeevKumar Sir, I have fixd bugs and all, Can you please checkout once?  #78

**Comment by AkshitGarg24** [comment]
@pranjalee30, the website has undergone some UI updates. Please update your branch and resolve any conflicts. I’ll review the PR once it's ready.

**Comment by pranjalee30** [comment]
> @pranjalee30, the website has undergone some UI updates. Please update your branch and resolve any conflicts. I’ll review the PR once it's ready.

Its all up to date, Kindly merge it

**Comment by AkshitGarg24** [comment]
Nope its not. You are 39 commits behind the main branch of this repo.

image

**Comment by AkshitGarg24** [comment]
And also, solve issues by making a new branch instead of working on the `main` branch.

**Pull request closed without merging**
