### PR TITLE
Contact form solution

### LINKED ISSUE #147: Implement Advanced Contact Form with Accessibility, Responsiveness, Real-time Validation, and Enhanced User Experience Description:
## Issue Overview:
I would like to contribute by implementing an advanced version of the contact form that aligns closely with the provided design specifications while enhancing accessibility, responsiveness, and user experience. This implementation will include dynamic error handling, screen reader support, keyboard navigation, and real-time validation, along with an option to save draft inputs locally.

## Proposed Solution:
The solution is from one of the frontend mentor challenges [Contact Form](https://www.frontendmentor.io/challenges/contact-form--G-hYlqKJj)
The project images are below

desktop-design

The solution will cover the following aspects:

**1. Accessibility Features:**

- Use aria-live regions to announce error messages and success messages for screen reader users.
- Implement aria-labels and aria-describedby attributes for form inputs to ensure clear instructions and context for screen readers.
- Manage focus state during validation errors and form submission, providing appropriate feedback for keyboard-only users.

**2. Form Validation:**

- Implement client-side form validation with real-time feedback for all input fields, including:
- Required fields check for "Name", "Email", and "Message".
- Real-time email validation using a regular expression pattern.
- Display error messages dynamically next to invalid input fields with smooth animations.

**3. Enhanced User Experience:**

- Create animated transitions for displaying and hiding error messages, using subtle fade-in and slide-in effects.
- Display a custom success toast message upon successful form submission, including:
- Dismiss button for manual closing.
- Auto-hide feature to remove the toast after 5 seconds.

focus-and-active-state
hover-state

**4. Responsive Design:**

- Implement responsive styling to ensure the form adapts to different screen sizes, providing an optimal experience on mobile, tablet, and desktop devices.
- Include media queries to adjust form layout, padding, and touch target sizes for accessibility on smaller screens.

mobile-design

**5. Save Draft Feature:**

- Allow users to save form input data locally using local storage, so they don’t lose progress if the page is accidentally refreshed or closed.
- Automatically load saved draft data when the user revisits the page, pre-filling the form with their previous inputs.
- Include a “Clear Draft” button to reset the form and clear local storage data if the user wishes to start over.

**6. Keyboard Navigation and Focus Management:**

- Ensure the form can be completed using only the keyboard by managing focus for each form element.
- Shift focus to the first invalid input upon form validation errors.
- Shift focus to the success toast message upon successful submission for better user feedback.

**7. Expected Outcome:**
The enhanced contact form will provide a smooth and accessible experience for all users, including those using screen readers or keyboard-only navigation. It will be responsive across various device sizes, offer real-time feedback during form input, and ensure no data is lost with the Save Draft feature. Additionally, subtle animations and dynamic error messages will contribute to an overall improved user experience.

@beRajeevKumar Let me know if I can proceed with this implementation or if there are additional guidelines or features, you’d like to include like what to name the project folder i.e 25-Contact-form. Thank you!

### PR DESCRIPTION
**Pull request by Titus210**
# Pull Request: Enhanced Contact Form Implementation
## What does this PR do?
This pull request introduces an enhanced version of the contact form, focusing on improving accessibility, responsiveness, and user experience. The solution aligns closely with the provided design specifications and incorporates several new features aimed at making the form more user-friendly.

Fixes #147 

### Motivation and Context
The goal of this implementation is to create a contact form that not only looks good but also provides a seamless experience for all users, including those with disabilities. By improving accessibility and user experience, we aim to ensure that everyone can interact with the form without difficulty.

### Dependencies
No additional dependencies are required for this change.

### Screenshots
desktop-error
mobile-solution

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?
To verify the changes, please follow these steps:
1. Check the accessibility features using a screen reader.
2. Fill out the form to test real-time validation for all input fields.
3. Submit the form and ensure the success message appears and disappears after 5 seconds.
4. Refresh the page to check if the saved draft is pre-filled in the form.

### Test Cases
- [ ] Test the accessibility of the form with various screen readers.
- [ ] Validate required fields and ensure dynamic error messages display correctly.
- [ ] Check the responsiveness of the form on different screen sizes.

## Request for Merge
@beRajeevKumar  I kindly request a review of this pull request and look forward to your feedback. If everything looks good, I would appreciate merging it into the main branch. Thank you for your time and support!

### CODE REVIEW

**Comment by AkshitGarg24** [comment]
@Titus210, I am unable to see the project on the main page. Can you please link the project so that it will visible on the main page.

**Comment by Titus210** [comment]
@AkshitGarg24 I'm not sure what you mean by linking the project. Would you kindly elaborate more clearly.
Should it be merged first for it to appear in the project window? Its currently running on a branch. `contact-form-solution` under the directory `25-contact-form`.

**Comment by Titus210** [comment]
> @AkshitGarg24 I'm not sure what you mean by linking the project. Would you kindly elaborate more clearly. Should it be merged first for it to appear in the project window? Its currently running on a branch. `contact-form-solution` under the directory `25-contact-form`.

The live demo link that i have included on the project description is from my own Netlify account.

**Comment by AkshitGarg24** [comment]
This is the link to the website that will be shown after merging your PR : [Link](https://deploy-preview-196--openfrontendmentor.netlify.app/).

After merging your PR, I should see some changes in the website, right? But I am unable to find any difference in the website. I guess you forgot to link the changes so as it should be visible on the main web-page.

**Comment by Titus210** [comment]
@AkshitGarg24 I have understood what you mean. Try merging the PR first then we see it updating on the main website, from my end this pull request isn't merged yet.
image

**Comment by AkshitGarg24** [comment]
The link provided shows how the website will appear after merging the PR. But for your convenience, I will merge the PR and then check the changes in the website.

**Comment by AkshitGarg24** [comment]
You can check the website now @Titus210.

**Comment by Titus210** [comment]
@AkshitGarg24 Thank you. However, i cannot also see the update on the website. Just for clarification...is there anything that I have missed out, I would appreciate if you took me through what is needed so that the website can be among other listed projects on the website?

**Comment by AkshitGarg24** [comment]
Have a look at the PR #163. I guess you will get the idea what you are missing out.

**Pull request merged**
