### PR TITLE
Fixed Image related issue and added a new page CSS Animation

### PR DESCRIPTION
**Pull request by Roshansuthar1105**
## What does this PR do?
1. Added a new page name CSS Animations , which contains several animations of CSS.
2. Fixed the image related issue in cards no 22 to 25.
 
### 1. Image related issue in cards no 22 to 25.
Before : 

image

After:

image

### 2. New Page Added : CSS Animations
image

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- Chore (refactoring code, technical debt, workflow improvements)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How should this be tested?

- [x] Test A : local preview
   Open `index.html` from folder `Frontend_mentor`

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by Roshansuthar1105** [comment]
Take a look on my work @beRajeevKumar

**Comment by beRajeevKumar** [comment]
I will review it soon

**Comment by Roshansuthar1105** [comment]
Please review my work @beRajeevKumar .

**Comment by Roshansuthar1105** [comment]
@beRajeevKumar take a look at this request, please.

**Pull request closed without merging**
