### PR TITLE
[Feat]: Added About us page to link to the footer

### LINKED ISSUE #480: [Feat] Add About us page to link to the footer
### Description

There is About us n the footer but is not linked to any page I would like to add this feature.
@beRajeevKumar please assign me this issue under gssoc-ext level and hacktoberfest-accecpted tags

### Screenshots

image
image

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/beRajeevKumar/Frontend_Mentor/blob/main/Code_Of_Conduct.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by Annapoornaaradhya**
Added About us page to link to the footer.

Fixes #480 

image

## Type of change

- New feature (non-breaking change which adds functional

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

@beRajeevKumar please assign me this issue under gssoc-ext level and hacktoberfest-accecpted tags

### CODE REVIEW

**Comment by Annapoornaaradhya** [comment]
@beRajeevKumar Can you please merge this PR

**Comment by beRajeevKumar** [comment]
But there is no change in the UI.

**Comment by Annapoornaaradhya** [comment]
@beRajeevKumar i have styled the about us page aswell
image

My issue was to add ABOUT US page linked in footer not change the UI

**Comment by Annapoornaaradhya** [comment]
@beRajeevKumar can you please merge PR

**Comment by Annapoornaaradhya** [comment]
@beRajeevKumar its been 2 weeks since i have raised the PR please look into it and merge.

**Comment by Annapoornaaradhya** [comment]
@beRajeevKumar can you please make it level 3 as its addition of new feature

**Pull request merged**
