### PR TITLE
Add NAVBAR

### LINKED ISSUE #80: Add NAVBAR!
### 404 no navbar found, **will add the NAVBAR to the website.**

For example (sample NAVBAR)
[https://kevindua26.github.io/EchoSync/](url)
Screenshot 2024-10-04 003008

@KiranBaliga @beRajeevKumar @J-B-Mugundh @himanshu-sheetlani @Ashmita-15

### PR DESCRIPTION
**Pull request by Kevindua26**
### Issue solved

- Close #80

### Added NAVBAR to the website

This pull request introduces a navigation bar to the "Frontend Mentor" website. The navbar includes links to the main sections, improving the site's usability and accessibility. It has been designed, ensuring a seamless user experience across devices, including desktop and mobile.

**Key Features:**
1. Clean and intuitive layout: Easy access to important sections.
2. Cross-browser compatibility: Tested on modern browsers to ensure consistent behavior.

Screenshot provided below-

Screenshot 2024-10-06 003143

### CODE REVIEW

**Comment by Kevindua26** [comment]
Hello @beRajeevKumar Here after opening a pr it is showing something conflicting my 1 file [index.html], can you help me how to get resolve of it.

**Comment by beRajeevKumar** [comment]
Nice work man👍

**Comment by AkshitGarg24** [comment]
@Kevindua26, the website has undergone some UI updates. Please update your branch and resolve any conflicts. I’ll review the PR once it's ready.

**Comment by Kevindua26** [comment]
@AkshitGarg24 okay I'll resolve it soon

**Pull request closed without merging**
