### PR TITLE
added gsap to animate website

### LINKED ISSUE #10: GSAP Text Animations on Homepage
**Objective**: I propose enhancing the homepage with text animations using GSAP (GreenSock Animation Platform) to improve user engagement and make the interface more dynamic.

**Details**:
- Animate heading and subheading text on page load.
- Include subtle fade-in or slide-in animations for improved visual appeal.
- Ensure animations are responsive and do not affect performance on lower-end devices.
- Will add comments to code to ensure clarity for future contributors.

Please assign this issue to me, as I would love to work on it. I am also a contributor in GGSOCExt 24 , hacktoberfest.

Looking forward to your feedback!

### PR DESCRIPTION
**Pull request by priyashuu**
fixes #10

### CODE REVIEW

**Review by beRajeevKumar — APPROVED** [review]

**Comment by beRajeevKumar** [comment]
@priyashuu, There are some merge conflicts in your PR, so regenerate the same PR again

**Comment by priyashuu** [comment]
done sir

**Comment by priyashuu** [comment]
there is no conflict in branch , so sir can you please merge the pr

**Comment by solopeer** [comment]
It looks great and sleek

**Comment by priyashuu** [comment]
its approved , can you please merge it

**Comment by AkshitGarg24** [comment]
The conflicts are not properly resolved. This is the link to the website which will be shown after merging your PR : [Link](https://deploy-preview-47--openfrontendmentor.netlify.app/). Compare it with the original link of the website.

**Comment by AkshitGarg24** [comment]
Here is the current link of the website : [Link](https://openfrontendmentor.netlify.app/). Now after your last commit the website is looking like this [Link](https://deploy-preview-47--openfrontendmentor.netlify.app/).

**Comment by priyashuu** [comment]
comparing the previous code with new code , its time consuming  , and also confusing me , can you please help me , how to resolve this in less time , i did some changes till now ,

**Pull request closed without merging**
