### PR TITLE
Add Expense Tracker Project

### LINKED ISSUE #469: [Feat] Add " Expense Tracker" website using HTML, CSS, React, and Context API
### Description

I would like to propose adding an expense tracker application to the project. This application will be built using HTML, CSS, and React, leveraging the Context API for state management instead of passing props down through components.

## Features

- **Add Expense:** Users can input details of their expenses.
- **View Expenses:** A list view of all recorded expenses.
- **Total Calculation:** Display the total amount of expenses.

## Benefits
Using the Context API will simplify state management across components and improve the scalability of the application as it grows.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/beRajeevKumar/Frontend_Mentor/blob/main/Code_Of_Conduct.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by riyaa060**
## What does this PR do?

This pull request introduces the Expense Tracker application, a web app built with React that allows users to manage their expenses effectively. It utilizes the Context API for state management, enabling features like adding, editing, and deleting expenses.

Fixes #469

Screenshot 2024-10-21 144527

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## How should this be tested?

**Steps to Test the Expense Tracker Application**
1. Clone the Repository: Open your terminal and clone the repository to your local machine by using the appropriate command for cloning a Git repository.

```bash
git clone https://github.com/yourusername/expense-tracker.git
```

2.  Navigate to the Project Directory: Change your current working directory to the project folder where you cloned the repository.
```bash
cd expense-tracker
```

4. ##Install Dependencies: Use a package manager like npm to install the required dependencies for the project.
```bash
npm install
```

5. Start the Development Server: Launch the application by starting the development server using the command provided in the project documentation.
```bash
npm start
```

7. Open the Application: Open your web browser and navigate to http://localhost:3000 to view the application.

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by beRajeevKumar** [comment]
@riyaa060 Please don't do it. 
It seems like it is a cloned project from Git Hub.

**Comment by beRajeevKumar** [comment]
this project doesn't show in the UI of the project.

**Comment by riyaa060** [comment]
Noo,I have made this few months back and just transfer the code to vs code today and commit. You can check my github

**Comment by riyaa060** [comment]
I am sending you a video

**Comment by riyaa060** [comment]
Sorry but i have rechecked evrerything try to run again using react command.

**Pull request closed without merging**
