### PR TITLE
05-interactive-rating-respoisve

### PR DESCRIPTION
**Pull request by jjf2009**
#26 
05-interactive-rating project is made responsive and also fixed bug where if the user submited the form without choosing any number is would take it was 4 
Screenshot
Screen Shot 2024-10-06 at 17 11 42
Screen Shot 2024-10-06 at 17 11 46
   
Kindly label this PR with gssoc-ext and hactobter and level 
Also label the PR that have been merged of mine please

### CODE REVIEW

**Comment by jjf2009** [comment]
@AkshitGarg24 kindly add labels to this pr

**Comment by AkshitGarg24** [comment]
@jjf2009, resolve conflicts, and update the branch.

**Comment by jjf2009** [comment]
@AkshitGarg24 conflicts are resloved add labels for this pr

**Comment by AkshitGarg24** [comment]
@jjf2009, this is the deployed link of the project after merging the PR : [Link](https://deploy-preview-138--openfrontendmentor.netlify.app/).
Compare it with the original website as it is making a lot of changes in the original website. Are you sure about the changes in the PR?

**Comment by jjf2009** [comment]
@AkshitGarg24 ok i will check

**Comment by jjf2009** [comment]
@AkshitGarg24 please check again i have fixed it on my side i have also added some git actions for greeting and auto labeling the issues with gssoc-ext and hacktober .

**Comment by AkshitGarg24** [comment]
Why have you deleted `Code_of_Conduct.md` file. And please do only those changes that are assigned to you as there are many contributors who wants to or might be working on the same issue.

**Comment by jjf2009** [comment]
@AkshitGarg24 i have removed the changes that was not assigned to me and have added the code of conduct md . Very sorry for my conduct

**Comment by AkshitGarg24** [comment]
Hey @jjf2009, no issues at all!! Take it easy. You haven't done anything wrong. Don't be sorry for this. Let @beRajeevKumar have a look at this PR. We will merge it soon. Till then, you can work on other issues.

**Comment by beRajeevKumar** [comment]
Please make some meaningful contributions that really impact the project and your skill set.

**Review by beRajeevKumar — COMMENTED** [review]
I had close this PR

**Pull request closed without merging**
